services:
  db:
    image: postgres-ai
    build:
      context: ./docker/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_ANON_ROLE=${DB_ANON_ROLE}
      - DB_SCHEMA=${DB_SCHEMA}
    volumes:
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d
      - pg_volume:/var/lib/postgresql/data
    networks:
      postgrest-backend:
    
  postgrest:
    image: postgrest/postgrest:latest
    ports:
      - "4000:3000"
    environment:
      - PGRST_DB_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - PGRST_DB_SCHEMA=${DB_SCHEMA}
      - PGRST_DB_ANON_ROLE=${DB_ANON_ROLE}
      - PGRST_OPENAPI_SERVER_PROXY_URI=http://localhost:3000
    networks:
      postgrest-backend:
    
networks:
  postgrest-backend:

volumes:
  pg_volume:
